### ISSUE TITLE
现在好像用不了了

### ISSUE THREAD

**Issue by sw1128** [Ezharjan/BJUTAntiCovidClocker#1]

**Comment by Ezharjan** [comment]
这都是啥时候的代码了……
![图片](https://user-images.githubusercontent.com/60126466/187842272-fb51068a-fffc-4a49-aa96-9a90b853cb6f.png)

现在此项目仅具备学习用途，不具备实际用途，欢迎提PR。

**Comment by sw1128** [comment]
你好，我最近在学习爬虫，bjut的打卡接口请求头里有一个字段为Authorization，能否请教一下这个字段是如何生成的，如能指教不胜感激
